annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2021.6.17
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: This chart is made based on bitnami/minio chart version 7.1.7 app version 2021.6.17. The major difference is this chart is using official minio image and improves gateway settings.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/minio
icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: minio
sources:
  - https://github.com/bitnami/bitnami-docker-minio
  - https://min.io
version: 7.1.7
